In [2]:
from tira_kws.constants import (
    CAPSTONE_CLOSE_NEGATIVE_RECORDS,
    RECORD_LIST_CSV,
)

import pandas as pd
from unidecode import unidecode

/home/markjos/projects/kws_tira/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
record_df = pd.read_csv(RECORD_LIST_CSV)
record_df.head()

,record_idx,recording_id,start,duration,channel,text,language,speaker,gloss,lemmata,translation,fst_normalized,unidecode_normalized
0,0,HH01082021,217.011,2.541,0,àprí jɜ̀dí ðáŋàlà,tic,Himidan,"boy[NOM,SG] touch[CLJ,VENT,PFV] sheep[ACC,SG,l...",àpɾí ɜd ðàŋàl,boy held sheep,àpɾí jɜ̀dí ðáŋàlà,apri jedi dangala
1,1,HH01082021,221.371,3.652,0,àprí jɜ̀dí ðáŋàlà,tic,Himidan,"boy[NOM,SG] touch[CLJ,VENT,PFV] sheep[ACC,SG,l...",àpɾí ɜd ðàŋàl,boy held sheep,àpɾí jɜ̀dí ðáŋàlà,apri jedi dangala
2,2,HH01082021,283.401,3.127,0,àprí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,tic,Himidan,"boy[NOM,SG] pull[CLJ,VENT,PFV] sheep[ACC,SG,le...",àpɾí vəlɛð ðàŋàl,boy pulled sheep (towards),àpɾí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,apri j@v@ledo dangala
3,3,HH01082021,288.835,2.745,0,àprí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,tic,Himidan,"boy[NOM,SG] pull[CLJ,VENT,PFV] sheep[ACC,SG,le...",àpɾí vəlɛð ðàŋàl,boy pulled sheep (towards),àpɾí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,apri j@v@ledo dangala
4,4,HH01082021,304.737,3.025,0,àprí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,tic,Himidan,"boy[NOM,SG] pull[CLJ,VENT,PFV] sheep[ACC,SG,le...",àpɾí vəlɛð ðàŋàl,boy pulled sheep (towards),àpɾí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,apri j@v@ledo dangala

## Revisions
Replace any malformed data from close negatives dataframe.

In [11]:
clneg_df = pd.read_csv(CAPSTONE_CLOSE_NEGATIVE_RECORDS)
clneg_df.head()

,keyword,keyword_id,sentence_id,translation,original_sentence,textnorm_sentence,audionorm_sentence,audio_quality,missing_speech,extra_speech,mistranscription,comment
0,àpɾí,NaN,18114,Kuku fed the boy food (and left),kúkù kǎjjì àpɾíɲá ŋɔ̀mɔ̀,kúkù kájì àpɾíɲá ŋɔ̀mɔ̀,kúkù kájì àpɾíɲá ŋɔ̀mɔ̀,3.0,False,False,False,NaN
1,àpɾí,NaN,18085,Kuku will make the boy call his mom,kúkù káútìðìjɔ̀ àpɾíɲá lɛ́ŋgɛ̀n,kúkù ká_útìðìjɔ̀ àpɾíɲá lɛ́ŋgɛ́n,kúkù ká_útìðìjɔ̀ àpɾíɲá lɛ́ŋgɛ́n,3.0,False,False,False,NaN
2,àpɾí,NaN,11766,Kuku made the boy break a stick (and left),kúkù kàgáɾíjì àpɾíɲá ðówɛ̀,kúkù kà_gáɾìjì àpɾíɲá ðówɛ́,kúkù kà_gáɾìjì àpɾíɲá ðówɛ́,3.0,False,False,False,NaN
3,àpɾí,NaN,6396,(dog) runs away from (the boy in the field),ŋɛ́n ŋɔ̂ɽàt̪àt̪ɛ́ àpɾíɲá nɛ̀ lə̀vɛ̀r,ŋɛ́n ŋɔ́ɽàt̪átɛ́ àpɾíɲá nɛ̀ lə̀və́r,ŋɛ́n ŋɔ́ɽàt̪átɛ́ àpɾíɲá nɛ̀ lə̀və́r,3.0,False,False,False,NaN
4,àpɾí,NaN,800,The sheep will pull the boy away tomorrow,ðàŋàl ðǎvə́lɛ̂ðà àpɾíɲá ndòbà,ðàŋàl ðá_və́lɛ̀ðà àpɾíɲá nd̪ɔ̀bà,ðàŋàl ðá_və́lɛ̀ðà àpɾíɲá nd̪ɔ̀bà,3.0,False,False,False,NaN

In [12]:
clneg_df['audio_quality'].value_counts()

audio_quality
3.0    100
Name: count, dtype: int64

In [ ]:
clneg_df['mistranscription'].value_counts()

mistranscription
False    100
Name: count, dtype: int64

In [15]:
clneg_df['missing_speech'].value_counts()

missing_speech
False    99
True      1
Name: count, dtype: int64

In [16]:
clneg_df['extra_speech'].value_counts()

extra_speech
False    100
Name: count, dtype: int64

All transcription mistakes have been corrected, and no audio quality issues are reported, so no revisions are needed.