In [1]:
from tira_kws.constants import (
    CAPSTONE_POSITIVE_RECORDS,
    RECORD_LIST_CSV,
)

import pandas as pd
from unidecode import unidecode

/home/markjos/projects/kws_tira/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
record_df = pd.read_csv(RECORD_LIST_CSV)
record_df.head()

,record_idx,recording_id,start,duration,channel,text,language,speaker,gloss,lemmata,translation,fst_normalized,unidecode_normalized
0,0,HH01082021,217.011,2.541,0,àprí jɜ̀dí ðáŋàlà,tic,Himidan,"boy[NOM,SG] touch[CLJ,VENT,PFV] sheep[ACC,SG,l...",àpɾí ɜd ðàŋàl,boy held sheep,àpɾí jɜ̀dí ðáŋàlà,apri jedi dangala
1,1,HH01082021,221.371,3.652,0,àprí jɜ̀dí ðáŋàlà,tic,Himidan,"boy[NOM,SG] touch[CLJ,VENT,PFV] sheep[ACC,SG,l...",àpɾí ɜd ðàŋàl,boy held sheep,àpɾí jɜ̀dí ðáŋàlà,apri jedi dangala
2,2,HH01082021,283.401,3.127,0,àprí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,tic,Himidan,"boy[NOM,SG] pull[CLJ,VENT,PFV] sheep[ACC,SG,le...",àpɾí vəlɛð ðàŋàl,boy pulled sheep (towards),àpɾí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,apri j@v@ledo dangala
3,3,HH01082021,288.835,2.745,0,àprí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,tic,Himidan,"boy[NOM,SG] pull[CLJ,VENT,PFV] sheep[ACC,SG,le...",àpɾí vəlɛð ðàŋàl,boy pulled sheep (towards),àpɾí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,apri j@v@ledo dangala
4,4,HH01082021,304.737,3.025,0,àprí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,tic,Himidan,"boy[NOM,SG] pull[CLJ,VENT,PFV] sheep[ACC,SG,le...",àpɾí vəlɛð ðàŋàl,boy pulled sheep (towards),àpɾí jə̀və̀lɛ̀ðɔ́ ðáŋàlà,apri j@v@ledo dangala

## Revisions
Replace any malformed data from positives dataframe.

In [3]:
pos_df = pd.read_csv(CAPSTONE_POSITIVE_RECORDS)
pos_df.head()

,keyword,keyword_id,sentence_id,translation,original_sentence,textnorm_sentence,audionorm_sentence,audio_quality,missing_speech,extra_speech,mistranscription,comment
0,àpɾí,0.0,484,The boy will pull me here tomorrow.,àpɾí jǎŋîvlɛ̀ðɔ́ ǹdòbàgɛ̀,àpɾí jáŋɛ̂_və̀lɛ̀ðɔ́ nd̪ɔ̀bàgɛ̀,àpɾí jáŋɛ̂_və̀lɛ̀ðɔ́ nd̪ɔ̀bàgɛ̀,3.0,False,False,False,NaN
1,àpɾí,NaN,4381,every boy broke his stick,kńnà àpɾí jɛ̀gàrɔ́ ðówɛ́ íðùn,kńnà àpɾí jɛ̀gàɾɔ́ ðówɛ́ íðùn,kńnà àpɾí jɛ̀gàɾɔ́ ðówɛ́ íðùn,3.0,False,False,False,NaN
2,àpɾí,NaN,6755,the boy wants to eat the meat,àpɾí jâdùɾɔ́ ðíjá ɛ́ðɛ̀,àpɾí já_d̪ùɾɔ́ ðíjá ɛ́ðɛ̀,àpɾí já_d̪ùɾɔ́ ðíjá ɛ́ðɛ̀,3.0,False,False,False,NaN
3,ðɔ̀mɔ̀cɔ̀,NaN,3326,The man wrestled him,kə̀bùlìjí ðɔ́mɔ̀cɔ̀,kə̀bùlìjí ðɔ́mɔ̀cɔ̀,kə̀bùlìjí ðɔ́mɔ̀cɔ̀,3.0,False,False,False,NaN
4,àpɾí,NaN,20254,the boy grandpa said the lion bit is small,àpɾí jáɾɔ́jɛ́ ùɾnɔ̀ t̪á jàmə̀ɾðɔ́ t̪ʊ̀li...,àpɾí jáɾɔ́jɛ́ ùrnɔ̀ t̪á jə̀mɛ̀ɾðɔ́ t̪ùdi...,àpɾí jáɾɔ́jɛ́ ùrnɔ̀ t̪á jə̀mɛ̀ɾðɔ́ LION j...,3.0,False,False,False,NaN

In [4]:
pos_df['audio_quality'].value_counts()

audio_quality
3.0    93
2.0     5
1.0     2
Name: count, dtype: int64

In [5]:
pos_df['mistranscription'].value_counts()

mistranscription
False    98
True      2
Name: count, dtype: int64

In [6]:
pos_df['missing_speech'].value_counts()

missing_speech
False    100
Name: count, dtype: int64

In [7]:
pos_df['extra_speech'].value_counts()

extra_speech
False    96
True      4
Name: count, dtype: int64

In [ ]:
pos_df[pos_df['mistranscription'] | pos_df['missing_speech'] | pos_df['extra_speech']]